spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:1111/realms/bank/protocol/openid-connect/certs
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "user"
    password: "user"
  config:
    import: optional:configserver:http://localhost:8012


server:
  port: 8083