version: '3.8'
services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - "2345:5432"
    volumes:
      - ~/apps/postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=userDB